### ISSUE TITLE
CODING: Sample code for log out purpose using javascript and php using localstorage

### ISSUE THREAD

**Issue by pash0107** [IT3A-2016/Bitsparks#15]
Just search "Sample code for logout purpose using php and javascript localstorage"

Noli, hanap ka ng sample code para dito. Yung code mismo gamit ang javscript.

**Comment by NoliJay** [comment]
if (localStorage) {

    // Add an event listener for form submissions

    document.getElementById('contactForm').addEventListener('submit', function() {

      // Get the value of the name field.

      var name = document.getElementById('name').value;

      // Save the name in localStorage.

      localStorage.setItem('name', name);
    });

  }

}
