### ISSUE TITLE
Research(Procedure): How to upload website in hostinger.ph

### ISSUE THREAD

**Issue by pash0107** [IT3A-2016/Bitsparks#16]
Design of the panel that can be use in log in and registration

**Comment by NoliJay** [comment]
![Capture.PNG](https://zube.io/files/IT3A-2016/85e5260561734b6bb74de22d37f643fa.png)

**Comment by NoliJay** [comment]
![2.PNG](https://zube.io/files/IT3A-2016/828028fef45185621e7eee9e7d33d40c.png)
![3.PNG](https://zube.io/files/IT3A-2016/ccc1a9b0c12ad13fec16478b6c268333.png)
![4.PNG](https://zube.io/files/IT3A-2016/9cbef9c3a5510c25b2628ece526e41b7.png)
![56.PNG](https://zube.io/files/IT3A-2016/e44b47f902bfa9e868f1210394cc2a4d.png)
![7.PNG](https://zube.io/files/IT3A-2016/c4eec63847562ba38175d98ad039cef0.png)
![8.PNG](https://zube.io/files/IT3A-2016/b2e32bf59b4e6e719dbcd5dc3ebe07a1.png)
![9.PNG](https://zube.io/files/IT3A-2016/94c6e083a67e57b0382cec899beab0cc.png)
