### ISSUE TITLE
Design of storyboard in users

### ISSUE THREAD

**Issue by pash0107** [IT3A-2016/Bitsparks#20]
Using HTML5, CSS, or also template from bootstrap

**Comment by pash0107** [comment]
Aileen, need natin nung mga pwede natin ilagay sa navigation ng users, for example is "view schedule", "profile viewing","change password", "log out".

Yan palang naiisip ko, Hahaha.
Pero gawa ka din ng plano para sa users. Kahit drawing palang, parang pag pinindot ko to, san na mapupunta. Ganun gets? :)

Kahit drawing lang, mahalaga toh sa user e.:D
Nagawa ko na yung sa admin. kaya madli nagawa.:)

Note: Kelangan mo muna magawa toh before yung isa mong issue.:)

**Comment by delrosarioaileen** [comment]
![userstoryboard](https://cloud.githubusercontent.com/assets/24487438/23327082/fc59db5e-fb40-11e6-84f1-409edd3358ad.PNG)
