### ISSUE TITLE
A web based landing page for the proposed system

### ISSUE THREAD

**Issue by pash0107** [IT3A-2016/Bitsparks#3]
Landing page

**Comment by pash0107** [comment]
![image](https://cloud.githubusercontent.com/assets/21094193/21921623/5d77ea34-d9a4-11e6-830e-ea734fdf75d7.png)

I'm actually created a design for the landing page. take a look for imrovements.:)

**Comment by NoliJay** [comment]
maganda na

**Comment by delrosarioaileen** [comment]
![landingpage](https://cloud.githubusercontent.com/assets/24487438/22324361/c4556c24-e3e3-11e6-8804-55b0fabac480.png)

comment na lang po kung approve sa inyo o may gustong ipabago :)
