### ISSUE TITLE
Research for masterfile database gathering: how to convert excel file table to sql file table format

### ISSUE THREAD

**Issue by pash0107** [IT3A-2016/Bitsparks#64]
Guys, I need the exact code . Just search "How to convert excel file table to sql file table"

**Comment by pash0107** [comment]
Note: Wag link ang ilagay nio, yung mismong naresearch nio. Slaamat

**Comment by NoliJay** [comment]
![19.PNG](https://zube.io/files/IT3A-2016/07674fca95bc27bb26cbe30d91f1691b.png)

**Comment by NoliJay** [comment]
![20.PNG](https://zube.io/files/IT3A-2016/cb144e0f1d66e3e0eee5162a9f30fd3f.png)

**Comment by NoliJay** [comment]
![21.PNG](https://zube.io/files/IT3A-2016/e261d5654517f305085a7b25eebe62be.png)

**Comment by NoliJay** [comment]
![22.PNG](https://zube.io/files/IT3A-2016/8590f3e0bcce67a05c0f3355c02ca4b2.png)

**Comment by NoliJay** [comment]
![23.PNG](https://zube.io/files/IT3A-2016/149bb38f00bff045bb38262f75d89094.png)

**Comment by NoliJay** [comment]
![24.PNG](https://zube.io/files/IT3A-2016/ba9071b895154e069c32838c838b48c6.png)

**Comment by NoliJay** [comment]
![25.PNG](https://zube.io/files/IT3A-2016/8f10f8b409fff439387f6e79e373eda3.png)

**Comment by NoliJay** [comment]
![26.PNG](https://zube.io/files/IT3A-2016/7c17e0014af949da1a1ee2b7eebd6046.png)

**Comment by NoliJay** [comment]
![27.PNG](https://zube.io/files/IT3A-2016/8eae722ee03c4a0e9b8dae80676d49e7.png)

**Comment by NoliJay** [comment]
<?php
$databasehost = "localhost"; 
$databasename = "test"; 
$databasetable = "sample"; 
$databaseusername="test"; 
$databasepassword = ""; 
$fieldseparator = ","; 
$lineseparator = "\n";
$csvfile = "filename.csv";
$addauto = 0;
$save = 1; 
$outputfile = "output.sql";        

        if(!file_exists($csvfile)) {    echo "File not found. Make sure you specified the correct path.\n";     exit; }

        $file = fopen($csvfile,"r");

        if(!$file) {    echo "Error opening data file.\n";  exit; }

        $size = filesize($csvfile);

        if(!$size) {    echo "File is empty.\n";    exit; }

        $csvcontent = fread($file,$size);

        fclose($file);

        $con = @mysql_connect($databasehost,$databaseusername,$databasepassword) or die(mysql_error()); @mysql_select_db($databasename) or die(mysql_error());

        $lines = 0; $queries = ""; $linearray = array();

        foreach(split($lineseparator,$csvcontent) as $line) {

            $lines++;

            $line = trim($line," \t");      $line = str_replace("\r","",$line);         /************************************   This line escapes the special character. remove it if entries are already escaped in the csv file   ************************************/   $line = str_replace("'","\'",$line);    /*************************************/         $linearray = explode($fieldseparator,$line);        $linemysql = implode("','",$linearray);         if($addauto)        $query = "insert into $databasetable values('','$linemysql');";     else        $query = "insert into $databasetable values('$linemysql');";        $queries .= $query . "\n";

            @mysql_query($query); }

        @mysql_close($con);

        if($save) {         if(!is_writable($outputfile)) {         echo "File is not writable, check permissions.\n";  }       else {      $file2 = fopen($outputfile,"w");
                        if(!$file2) {           echo "Error writing to the output file.\n";         }       else {          fwrite($file2,$queries);            fclose($file2);         }   }    }

        echo "Found a total of $lines records in this csv file.\n";


        ?>
